site_name: Traces Analyzer
theme: readthedocs

nav:
- Introduction: 'index.md'
- 'parsing.md'
- 'feature_extraction.md'
- 'definitions.md'
- 'contract_attribution.md'

markdown_extensions:
- admonition
- plantuml_markdown:
    server: http://www.plantuml.com/plantuml  # PlantUML server, for remote rendering
